
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 19;
  public static final int ANIM = 10;
  public static final int SMENOS = 3;
  public static final int PARI = 6;
  public static final int CURVA = 18;
  public static final int COLOR = 17;
  public static final int SMAS = 2;
  public static final int PARD = 7;
  public static final int RECT = 15;
  public static final int GRAFICAR = 8;
  public static final int SDIVI = 5;
  public static final int POLIG = 16;
  public static final int COMA = 9;
  public static final int EOF = 0;
  public static final int OBJ = 11;
  public static final int CUAD = 14;
  public static final int NUMERO = 20;
  public static final int error = 1;
  public static final int ANT = 12;
  public static final int SMULT = 4;
  public static final int CIRC = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SMAS",
  "SMENOS",
  "SMULT",
  "SDIVI",
  "PARI",
  "PARD",
  "GRAFICAR",
  "COMA",
  "ANIM",
  "OBJ",
  "ANT",
  "CIRC",
  "CUAD",
  "RECT",
  "POLIG",
  "COLOR",
  "CURVA",
  "LINEA",
  "NUMERO"
  };
}

